### ISSUE TITLE
INSTALLATION ERROR

### ISSUE THREAD

**Issue by endurasek** [robertsLando/node-red-contrib-m-bus#24]
Hello everyone
When I try to install node-red it gives me this message.
Has anyone an idea what could be wrong?

2022-12-07T05:08:50.977Z Install : node-red-contrib-m-bus 3.0.0

2022-12-07T05:08:50.407Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-m-bus@3.0.0
2022-12-07T05:08:52.160Z [err] npm
2022-12-07T05:08:52.162Z [err]  WARN 
2022-12-07T05:08:52.162Z [err] config production Use `--omit=dev` instead.
2022-12-07T05:08:55.835Z [err] npm 
2022-12-07T05:08:55.835Z [err] ERR!
2022-12-07T05:08:55.835Z [err]  code 1
2022-12-07T05:08:55.836Z [err] npm 
2022-12-07T05:08:55.837Z [err] ERR! path
2022-12-07T05:08:55.837Z [err]  /config/node-red/node_modules/node-mbus
2022-12-07T05:08:55.842Z [err] npm ERR!
2022-12-07T05:08:55.843Z [err]  command failed
2022-12-07T05:08:55.843Z [err] npm 
2022-12-07T05:08:55.844Z [err] ERR! command sh -c node-gyp rebuild
2022-12-07T05:08:55.844Z [err] npm ERR!
2022-12-07T05:08:55.844Z [err]  gyp info it worked if it ends with ok
2022-12-07T05:08:55.844Z [err] npm 
2022-12-07T05:08:55.845Z [err] ERR! gyp info using node-gyp@9.0.0
2022-12-07T05:08:55.845Z [err] npm ERR! gyp info using node@16.17.1 | linux | arm64
2022-12-07T05:08:55.845Z [err] npm ERR! gyp ERR! find Python 
2022-12-07T05:08:55.845Z [err] npm ERR!
2022-12-07T05:08:55.846Z [err]  gyp ERR! find Python checking Python explicitly set from command line or npm configuration
2022-12-07T05:08:55.846Z [err] npm ERR! gyp ERR! find Python - "--python=" or "npm config get python" is "/usr/bin/python3"
2022-12-07T05:08:55.846Z [err] npm ERR! gyp ERR! find Python - "/usr/bin/python3" is not in PATH or produced an error
2022-12-07T05:08:55.846Z [err] npm 
2022-12-07T05:08:55.846Z [err] ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
2022-12-07T05:08:55.846Z [err] npm ERR!
2022-12-07T05:08:55.846Z [err]  gyp ERR! find Python checking if "python3" can be used
2022-12-07T05:08:55.846Z [err] npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
2022-12-07T05:08:55.846Z [err] npm ERR! gyp ERR! find Python checking if "python" can be used
2022-12-07T05:08:55.846Z [err] npm 
2022-12-07T05:08:55.846Z [err] ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
2022-12-07T05:08:55.846Z [err] npm ERR!
2022-12-07T05:08:55.846Z [err]  gyp ERR! find Python 
2022-12-07T05:08:55.846Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-12-07T05:08:55.846Z [err] npm
2022-12-07T05:08:55.847Z [err]  ERR! gyp ERR! find Python You need to install the latest version of Python.
2022-12-07T05:08:55.847Z [err] npm 
2022-12-07T05:08:55.847Z [err] ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2022-12-07T05:08:55.847Z [err] npm ERR!
2022-12-07T05:08:55.847Z [err]  gyp ERR! find Python you can try one of the following options:
2022-12-07T05:08:55.847Z [err] npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2022-12-07T05:08:55.847Z [err] npm
2022-12-07T05:08:55.847Z [err]  ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
2022-12-07T05:08:55.847Z [err] npm 
2022-12-07T05:08:55.847Z [err] ERR! gyp ERR! find Python - Set the environment variable PYTHON
2022-12-07T05:08:55.847Z [err] npm ERR!
2022-12-07T05:08:55.847Z [err]  gyp ERR! find Python - Set the npm configuration variable python:
2022-12-07T05:08:55.847Z [err] npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
2022-12-07T05:08:55.848Z [err] npm ERR!
2022-12-07T05:08:55.848Z [err]  gyp ERR! find Python For more information consult the documentation at:
2022-12-07T05:08:55.848Z [err] npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2022-12-07T05:08:55.848Z [err] npm ERR! gyp ERR! find Python **********************************************************
2022-12-07T05:08:55.848Z [err] npm ERR!
2022-12-07T05:08:55.848Z [err]  gyp ERR! find Python 
2022-12-07T05:08:55.848Z [err] npm ERR! gyp ERR! configure error 
2022-12-07T05:08:55.848Z [err] npm
2022-12-07T05:08:55.848Z [err]  ERR! gyp ERR! stack Error: Could not find any Python installation to use
2022-12-07T05:08:55.848Z [err] npm 
2022-12-07T05:08:55.848Z [err] ERR! gyp ERR! stack     at PythonFinder.fail (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
2022-12-07T05:08:55.848Z [err] npm ERR!
2022-12-07T05:08:55.848Z [err]  gyp ERR! stack     at PythonFinder.runChecks (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
2022-12-07T05:08:55.848Z [err] npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
2022-12-07T05:08:55.849Z [err] npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
2022-12-07T05:08:55.849Z [err] npm
2022-12-07T05:08:55.849Z [err]  ERR! gyp ERR! stack     at exithandler (node:child_process:408:5)
2022-12-07T05:08:55.849Z [err] npm 
2022-12-07T05:08:55.849Z [err] ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:420:5)
2022-12-07T05:08:55.849Z [err] npm ERR!
2022-12-07T05:08:55.849Z [err]  gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
2022-12-07T05:08:55.849Z [err] npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
2022-12-07T05:08:55.849Z [err] npm
2022-12-07T05:08:55.849Z [err]  ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
2022-12-07T05:08:55.849Z [err] npm 
2022-12-07T05:08:55.849Z [err] ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
2022-12-07T05:08:55.849Z [err] npm ERR!
2022-12-07T05:08:55.849Z [err]  gyp ERR! System Linux 5.15.61-v8
2022-12-07T05:08:55.849Z [err] npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-12-07T05:08:55.850Z [err] npm ERR! gyp ERR! cwd /config/node-red/node_modules/node-mbus
2022-12-07T05:08:55.850Z [err] npm 
2022-12-07T05:08:55.850Z [err] ERR! gyp ERR! node -v v16.17.1
2022-12-07T05:08:55.850Z [err] npm ERR!
2022-12-07T05:08:55.850Z [err]  gyp ERR! node-gyp -v v9.0.0
2022-12-07T05:08:55.850Z [err] npm ERR! gyp ERR! not ok
2022-12-07T05:08:55.857Z [err] 
2022-12-07T05:08:55.858Z [err] npm ERR! A complete log of this run can be found in:
2022-12-07T05:08:55.858Z [err] npm ERR!     /root/.npm/_logs/2022-12-07T05_08_52_006Z-debug-0.log
2022-12-07T05:08:55.883Z rc=1

**Comment by endurasek** [comment]
thank you for the quick reply.  I'll try it as soon as I get home

śr., 7 gru 2022, 08:16 użytkownik Daniel Lando ***@***.***>
napisał:

**Comment by LoghinAndrei** [comment]
Solution for Home Assistant Node-Red Add-on users. Add python3 to system_packages is the add-on's configuration.

**Comment by endurasek** [comment]
Hello
I have to come back to the topic because I couldn't install .
I wanted to add that Node Red is installed on Raspberry Pi4 and the
commands you wrote don't work.
I don't know much about programming and I would like to ask for an
explanation of how to fix it in a simple way.

pt., 16 gru 2022 o 16:48 Daniel Lando ***@***.***> napisał(a):

**Comment by robertsLando** [comment]
Did you follow this steps? https://github.com/robertsLando/node-red-contrib-m-bus/issues/24#issuecomment-1340500726

**Comment by endurasek** [comment]
Hello
Home assistant does not support these commands

pt., 19 maj 2023, 11:58 użytkownik Daniel Lando ***@***.***>
napisał:

**Comment by LoghinAndrei** [comment]
Hello,

If in Home Assistant on the add-on's configuration tab press the 3-dot symbol -> edit in YAML and add python3 to system_packages as mentioned in comment https://github.com/robertsLando/node-red-contrib-m-bus/issues/24#issuecomment-1354971202 . See attached screenshot. 
![image](https://github.com/robertsLando/node-red-contrib-m-bus/assets/95474144/0eaf3b97-88a1-4b55-831a-a35bef436561)

**Comment by endurasek** [comment]
023-05-19T11:35:55.684Z Install : node-red-contrib-m-bus 3.0.0

2023-05-19T11:33:59.434Z npm install --no-audit --no-update-notifier
--no-fund --save --save-prefix=~ --production --engine-strict
***@***.***
2023-05-19T11:34:01.122Z [err] npm
2023-05-19T11:34:01.124Z [err]  WARN config
2023-05-19T11:34:01.124Z [err]  production Use `--omit=dev` instead.
2023-05-19T11:34:11.820Z [err] npm
2023-05-19T11:34:11.821Z [err] ERR! code 1
2023-05-19T11:34:11.821Z [err] npm ERR! path
/config/node-red/node_modules/node-mbus
2023-05-19T11:34:11.828Z [err] npm ERR! command failed
2023-05-19T11:34:11.829Z [err] npm ERR! command
2023-05-19T11:34:11.830Z [err]  sh -c node-gyp rebuild
2023-05-19T11:34:11.830Z [err] npm ERR! gyp info it worked if it ends with
ok
2023-05-19T11:34:11.830Z [err] npm ERR! gyp info using ***@***.***
2023-05-19T11:34:11.830Z [err] npm
2023-05-19T11:34:11.831Z [err]  ERR! gyp info using ***@***.*** | linux |
arm64
2023-05-19T11:34:11.831Z [err] npm ERR! gyp info find Python using Python
version 3.11.3 found at "/usr/bin/python3"
2023-05-19T11:34:11.831Z [err] npm ERR!
2023-05-19T11:34:11.832Z [err]  gyp info spawn /usr/bin/python3
2023-05-19T11:34:11.832Z [err] npm ERR! gyp info spawn args [
2023-05-19T11:34:11.832Z [err] npm ERR!
2023-05-19T11:34:11.832Z [err]  gyp info spawn args
'/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2023-05-19T11:34:11.832Z [err] npm ERR! gyp info spawn args   'binding.gyp',
2023-05-19T11:34:11.832Z [err] npm
2023-05-19T11:34:11.832Z [err]  ERR! gyp info spawn args   '-f',
2023-05-19T11:34:11.832Z [err] npm ERR!
2023-05-19T11:34:11.832Z [err]  gyp info spawn args   'make',
2023-05-19T11:34:11.832Z [err] npm ERR! gyp info spawn args   '-I',
2023-05-19T11:34:11.832Z [err] npm
2023-05-19T11:34:11.832Z [err]  ERR! gyp info spawn args
'/config/node-red/node_modules/node-mbus/build/config.gypi',
2023-05-19T11:34:11.832Z [err] npm ERR!
2023-05-19T11:34:11.833Z [err]  gyp info spawn args   '-I',
2023-05-19T11:34:11.833Z [err] npm ERR! gyp info spawn args
'/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2023-05-19T11:34:11.833Z [err] npm
2023-05-19T11:34:11.833Z [err] ERR! gyp info spawn args   '-I',
2023-05-19T11:34:11.833Z [err] npm ERR!
2023-05-19T11:34:11.833Z [err]  gyp info spawn args
'/root/.cache/node-gyp/18.16.0/include/node/common.gypi',
2023-05-19T11:34:11.833Z [err] npm ERR! gyp info spawn args
'-Dlibrary=shared_library',
2023-05-19T11:34:11.833Z [err] npm
2023-05-19T11:34:11.833Z [err] ERR! gyp info spawn args
'-Dvisibility=default',
2023-05-19T11:34:11.833Z [err] npm ERR! gyp info spawn args
'-Dnode_root_dir=/root/.cache/node-gyp/18.16.0',
2023-05-19T11:34:11.833Z [err] npm ERR! gyp info spawn args
'-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2023-05-19T11:34:11.833Z [err] npm
2023-05-19T11:34:11.834Z [err] ERR! gyp info spawn args
'-Dnode_lib_file=/root/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',
2023-05-19T11:34:11.834Z [err] npm ERR!
2023-05-19T11:34:11.834Z [err]  gyp info spawn args
'-Dmodule_root_dir=/config/node-red/node_modules/node-mbus',
2023-05-19T11:34:11.834Z [err] npm ERR! gyp info spawn args
'-Dnode_engine=v8',
2023-05-19T11:34:11.834Z [err] npm
2023-05-19T11:34:11.834Z [err] ERR! gyp info spawn args   '--depth=.',
2023-05-19T11:34:11.834Z [err] npm ERR!
2023-05-19T11:34:11.834Z [err]  gyp info spawn args   '--no-parallel',
2023-05-19T11:34:11.834Z [err] npm ERR! gyp info spawn args
'--generator-output',
2023-05-19T11:34:11.834Z [err] npm
2023-05-19T11:34:11.834Z [err]  ERR! gyp info spawn args   'build',
2023-05-19T11:34:11.834Z [err] npm ERR!
2023-05-19T11:34:11.834Z [err]  gyp info spawn args   '-Goutput_dir=.'
2023-05-19T11:34:11.834Z [err] npm ERR! gyp info spawn args ]
2023-05-19T11:34:11.835Z [err] npm ERR! gyp ERR! build error
2023-05-19T11:34:11.835Z [err] npm ERR! gyp ERR! stack Error: not found:
make
2023-05-19T11:34:11.835Z [err] npm
2023-05-19T11:34:11.835Z [err]  ERR! gyp ERR! stack     at getNotFoundError
(/usr/lib/node_modules/npm
/node_modules/node-gyp/node_modules/which/which.js:10:17)
2023-05-19T11:34:11.835Z [err] npm ERR!
2023-05-19T11:34:11.835Z [err]  gyp ERR! stack     at /usr/lib/node_modules/
npm/node_modules/node-gyp/node_modules/which/which.js:57:18
2023-05-19T11:34:11.835Z [err] npm ERR! gyp ERR! stack     at new Promise
(<anonymous>)
2023-05-19T11:34:11.835Z [err] npm
2023-05-19T11:34:11.835Z [err]  ERR! gyp ERR! stack     at step
(/usr/lib/node_modules/npm
/node_modules/node-gyp/node_modules/which/which.js:54:21)
2023-05-19T11:34:11.835Z [err] npm ERR!
2023-05-19T11:34:11.835Z [err]  gyp ERR! stack     at /usr/lib/node_modules/
npm/node_modules/node-gyp/node_modules/which/which.js:71:22
2023-05-19T11:34:11.835Z [err] npm ERR! gyp ERR! stack     at new Promise
(<anonymous>)
2023-05-19T11:34:11.835Z [err] npm
2023-05-19T11:34:11.836Z [err]  ERR! gyp ERR! stack     at subStep
(/usr/lib/node_modules/npm
/node_modules/node-gyp/node_modules/which/which.js:69:33)
2023-05-19T11:34:11.836Z [err] npm ERR!
2023-05-19T11:34:11.836Z [err]  gyp ERR! stack     at /usr/lib/node_modules/
npm/node_modules/node-gyp/node_modules/which/which.js:80:22
2023-05-19T11:34:11.836Z [err] npm ERR! gyp ERR! stack     at
/usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2023-05-19T11:34:11.836Z [err] npm
2023-05-19T11:34:11.836Z [err] ERR! gyp ERR! stack     at
/usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2023-05-19T11:34:11.836Z [err] npm ERR! gyp ERR! System Linux 6.1.21-v8
2023-05-19T11:34:11.836Z [err] npm ERR! gyp ERR! command "/usr/bin/node"
"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2023-05-19T11:34:11.836Z [err] npm
2023-05-19T11:34:11.836Z [err] ERR! gyp ERR! cwd
/config/node-red/node_modules/node-mbus
2023-05-19T11:34:11.836Z [err] npm ERR!
2023-05-19T11:34:11.837Z [err]  gyp ERR! node -v v18.16.0
2023-05-19T11:34:11.837Z [err] npm ERR! gyp ERR! node-gyp -v v9.3.1
2023-05-19T11:34:11.837Z [err] npm ERR! gyp ERR! not ok
2023-05-19T11:34:11.843Z [err]
2023-05-19T11:34:11.844Z [err] npm ERR! A complete log of this run can be
found in: /root/.npm/_logs/2023-05-19T11_34_00_976Z-debug-0.log
2023-05-19T11:34:11.901Z rc=1



pt., 19 maj 2023 o 12:23 LoghinAndrei ***@***.***> napisał(a):

**Comment by LoghinAndrei** [comment]
Can we have a look at your configuration?

**Comment by endurasek** [comment]
You mean this config?

pt., 19 maj 2023 o 15:02 LoghinAndrei ***@***.***> napisał(a):

**Comment by endurasek** [comment]
2023-05-19T16:27:55.578Z Install : node-red-contrib-m-bus 3.0.0

2023-05-19T16:27:53.746Z npm install --no-audit --no-update-notifier
--no-fund --save --save-prefix=~ --production --engine-strict
***@***.***
2023-05-19T16:27:55.339Z [err] npm
2023-05-19T16:27:55.340Z [err]  WARN config production Use `--omit=dev`
instead.
2023-05-19T16:28:05.813Z [err] npm
2023-05-19T16:28:05.814Z [err]
2023-05-19T16:28:05.814Z [err] ERR!
2023-05-19T16:28:05.814Z [err]
2023-05-19T16:28:05.815Z [err] code
2023-05-19T16:28:05.815Z [err]  1
2023-05-19T16:28:05.816Z [err] npm
2023-05-19T16:28:05.816Z [err]
2023-05-19T16:28:05.816Z [err] ERR!
2023-05-19T16:28:05.817Z [err]
2023-05-19T16:28:05.817Z [err] path
2023-05-19T16:28:05.817Z [err]  /config/node-red/node_modules/node-mbus
2023-05-19T16:28:05.825Z [err] npm
2023-05-19T16:28:05.825Z [err]
2023-05-19T16:28:05.826Z [err] ERR!
2023-05-19T16:28:05.826Z [err]  command failed
2023-05-19T16:28:05.827Z [err] npm
2023-05-19T16:28:05.827Z [err]
2023-05-19T16:28:05.828Z [err] ERR!
2023-05-19T16:28:05.828Z [err]
2023-05-19T16:28:05.829Z [err] command
2023-05-19T16:28:05.829Z [err]  sh -c node-gyp rebuild
2023-05-19T16:28:05.830Z [err] npm
2023-05-19T16:28:05.830Z [err]
2023-05-19T16:28:05.830Z [err] ERR!
2023-05-19T16:28:05.830Z [err]  gyp info it worked if it ends with ok
2023-05-19T16:28:05.831Z [err] npm
2023-05-19T16:28:05.831Z [err]
2023-05-19T16:28:05.831Z [err] ERR!
2023-05-19T16:28:05.831Z [err]  gyp info using ***@***.***
2023-05-19T16:28:05.831Z [err] npm
2023-05-19T16:28:05.832Z [err]
2023-05-19T16:28:05.832Z [err] ERR!
2023-05-19T16:28:05.832Z [err]  gyp info using ***@***.*** | linux | arm64
2023-05-19T16:28:05.832Z [err] npm
2023-05-19T16:28:05.832Z [err]
2023-05-19T16:28:05.832Z [err] ERR!
2023-05-19T16:28:05.833Z [err]  gyp info find Python using Python version
3.11.3 found at "/usr/bin/python3"
2023-05-19T16:28:05.834Z [err] npm
2023-05-19T16:28:05.834Z [err]
2023-05-19T16:28:05.834Z [err] ERR!
2023-05-19T16:28:05.834Z [err]  gyp info spawn /usr/bin/python3
2023-05-19T16:28:05.835Z [err] npm
2023-05-19T16:28:05.835Z [err]
2023-05-19T16:28:05.836Z [err] ERR!
2023-05-19T16:28:05.836Z [err]  gyp info spawn args [
2023-05-19T16:28:05.836Z [err] npm
2023-05-19T16:28:05.837Z [err]
2023-05-19T16:28:05.837Z [err] ERR!
2023-05-19T16:28:05.837Z [err]  gyp info spawn args
'/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2023-05-19T16:28:05.837Z [err] npm
2023-05-19T16:28:05.838Z [err]
2023-05-19T16:28:05.838Z [err] ERR!
2023-05-19T16:28:05.838Z [err]  gyp info spawn args   'binding.gyp',
2023-05-19T16:28:05.838Z [err] npm
2023-05-19T16:28:05.839Z [err]
2023-05-19T16:28:05.839Z [err] ERR!
2023-05-19T16:28:05.839Z [err]  gyp info spawn args   '-f',
2023-05-19T16:28:05.839Z [err] npm
2023-05-19T16:28:05.839Z [err]
2023-05-19T16:28:05.839Z [err] ERR!
2023-05-19T16:28:05.840Z [err]  gyp info spawn args   'make',
2023-05-19T16:28:05.840Z [err] npm
2023-05-19T16:28:05.840Z [err]
2023-05-19T16:28:05.840Z [err] ERR!
2023-05-19T16:28:05.841Z [err]  gyp info spawn args   '-I',
2023-05-19T16:28:05.841Z [err] npm
2023-05-19T16:28:05.841Z [err]
2023-05-19T16:28:05.841Z [err] ERR!
2023-05-19T16:28:05.841Z [err]  gyp info spawn args
'/config/node-red/node_modules/node-mbus/build/config.gypi',
2023-05-19T16:28:05.842Z [err] npm
2023-05-19T16:28:05.842Z [err]
2023-05-19T16:28:05.842Z [err] ERR!
2023-05-19T16:28:05.842Z [err]  gyp info spawn args   '-I',
2023-05-19T16:28:05.842Z [err] npm
2023-05-19T16:28:05.842Z [err]
2023-05-19T16:28:05.843Z [err] ERR!
2023-05-19T16:28:05.843Z [err]  gyp info spawn args
'/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2023-05-19T16:28:05.843Z [err] npm
2023-05-19T16:28:05.843Z [err]
2023-05-19T16:28:05.843Z [err] ERR!
2023-05-19T16:28:05.843Z [err]  gyp info spawn args   '-I',
2023-05-19T16:28:05.844Z [err] npm
2023-05-19T16:28:05.844Z [err]
2023-05-19T16:28:05.844Z [err] ERR!
2023-05-19T16:28:05.844Z [err]  gyp info spawn args
'/root/.cache/node-gyp/18.16.0/include/node/common.gypi',
2023-05-19T16:28:05.845Z [err] npm
2023-05-19T16:28:05.845Z [err]
2023-05-19T16:28:05.845Z [err] ERR!
2023-05-19T16:28:05.846Z [err]  gyp info spawn args
'-Dlibrary=shared_library',
2023-05-19T16:28:05.846Z [err] npm ERR! gyp info spawn args
'-Dvisibility=default',
2023-05-19T16:28:05.846Z [err] npm ERR! gyp info spawn args
'-Dnode_root_dir=/root/.cache/node-gyp/18.16.0',
2023-05-19T16:28:05.846Z [err] npm ERR! gyp info spawn args
'-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
2023-05-19T16:28:05.846Z [err] npm ERR! gyp info spawn args
'-Dnode_lib_file=/root/.cache/node-gyp/18.16.0/<(target_arch)/node.lib',
2023-05-19T16:28:05.846Z [err] npm ERR! gyp info spawn args
'-Dmodule_root_dir=/config/node-red/node_modules/node-mbus',
2023-05-19T16:28:05.846Z [err] npm ERR! gyp info spawn args
'-Dnode_engine=v8',
2023-05-19T16:28:05.846Z [err] npm ERR! gyp info spawn args   '--depth=.',
2023-05-19T16:28:05.846Z [err] npm
2023-05-19T16:28:05.847Z [err] ERR! gyp info spawn args   '--no-parallel',
2023-05-19T16:28:05.847Z [err] npm ERR! gyp info spawn args
'--generator-output',
2023-05-19T16:28:05.847Z [err] npm ERR!
2023-05-19T16:28:05.847Z [err]  gyp info spawn args   'build',
2023-05-19T16:28:05.847Z [err] npm ERR!
2023-05-19T16:28:05.847Z [err]  gyp info spawn args   '-Goutput_dir=.'
2023-05-19T16:28:05.847Z [err] npm ERR!
2023-05-19T16:28:05.847Z [err]  gyp info spawn args ]
2023-05-19T16:28:05.847Z [err] npm
2023-05-19T16:28:05.847Z [err] ERR! gyp ERR! build error
2023-05-19T16:28:05.847Z [err] npm ERR!
2023-05-19T16:28:05.847Z [err]  gyp ERR! stack Error: not found: make
2023-05-19T16:28:05.847Z [err] npm
2023-05-19T16:28:05.847Z [err] ERR! gyp ERR! stack     at getNotFoundError
(/usr/lib/node_modules/npm
/node_modules/node-gyp/node_modules/which/which.js:10:17)
2023-05-19T16:28:05.847Z [err] npm
2023-05-19T16:28:05.847Z [err]  ERR! gyp ERR! stack     at
/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:
57:18
2023-05-19T16:28:05.847Z [err] npm
2023-05-19T16:28:05.847Z [err]  ERR! gyp ERR! stack     at new Promise
(<anonymous>)
2023-05-19T16:28:05.848Z [err] npm ERR!
2023-05-19T16:28:05.848Z [err]  gyp ERR! stack     at step
(/usr/lib/node_modules/npm
/node_modules/node-gyp/node_modules/which/which.js:54:21)
2023-05-19T16:28:05.848Z [err] npm
2023-05-19T16:28:05.848Z [err] ERR! gyp ERR! stack     at
/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/which/which.js:
71:22
2023-05-19T16:28:05.848Z [err] npm
2023-05-19T16:28:05.848Z [err] ERR! gyp ERR! stack     at new Promise
(<anonymous>)
2023-05-19T16:28:05.848Z [err] npm
2023-05-19T16:28:05.848Z [err]  ERR! gyp ERR! stack     at subStep
(/usr/lib/node_modules/npm
/node_modules/node-gyp/node_modules/which/which.js:69:33)
2023-05-19T16:28:05.848Z [err] npm ERR!
2023-05-19T16:28:05.848Z [err]  gyp ERR! stack     at /usr/lib/node_modules/
npm/node_modules/node-gyp/node_modules/which/which.js:80:22
2023-05-19T16:28:05.848Z [err] npm ERR!
2023-05-19T16:28:05.848Z [err]  gyp ERR! stack     at /usr/lib/node_modules/
npm/node_modules/isexe/index.js:42:5
2023-05-19T16:28:05.848Z [err] npm
2023-05-19T16:28:05.848Z [err]  ERR! gyp ERR! stack     at
/usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2023-05-19T16:28:05.848Z [err] npm
2023-05-19T16:28:05.851Z [err]  ERR! gyp ERR! System Linux 6.1.21-v8
2023-05-19T16:28:05.851Z [err] npm ERR! gyp ERR! command "/usr/bin/node"
"/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2023-05-19T16:28:05.851Z [err] npm ERR! gyp ERR! cwd
/config/node-red/node_modules/node-mbus
2023-05-19T16:28:05.851Z [err] npm ERR! gyp ERR! node -v v18.16.0
2023-05-19T16:28:05.851Z [err] npm ERR! gyp ERR! node-gyp -v v9.3.1
2023-05-19T16:28:05.851Z [err] npm ERR! gyp ERR! not ok
2023-05-19T16:28:05.858Z [err]
2023-05-19T16:28:05.860Z [err] npm ERR! A complete log of this run can be
found in: /root/.npm/_logs/2023-05-19T16_27_55_199Z-debug-0.log
2023-05-19T16:28:05.912Z rc=1

pt., 19 maj 2023 o 18:27 Endurasek s ***@***.***> napisał(a):

**Comment by endurasek** [comment]
ok now it works!!!
I installed everything from your  system_packages , not just python3.
Thank you very much for your help!!

system_packages:
  - python3
  - g++
  - gcc
  - make
  - linux-headers

pt., 19 maj 2023 o 18:30 Endurasek s ***@***.***> napisał(a):

**Comment by endurasek** [comment]
Hello
Finally got mbus-rs485 converter. But I have a problem with setting the
working parameters. Where can I change parameters like pariti: none/even???

pt., 19 maj 2023 o 18:55 Endurasek s ***@***.***> napisał(a):

**Comment by robertsLando** [comment]
You cannot set the parity, only the baud rate

**Comment by endurasek** [comment]
so what is the default setting?

pt., 26 maj 2023, 08:24 użytkownik Daniel Lando ***@***.***>
napisał:

**Comment by robertsLando** [comment]
8E1 if I remember correctly

**Comment by endurasek** [comment]
👍👍👍👍

pt., 26 maj 2023, 08:36 użytkownik Daniel Lando ***@***.***>
napisał:

**Comment by endurasek** [comment]
Hello
I finally got my energy meter after repair and I can start working. I see
that nod-red detects my meter but it only shows 12 basic information. How
can I send a specific query to my meter, e.g. 68 03 03 68 53 01 b1 05 16?

Regards
Roman

pt., 26 maj 2023 o 08:46 Endurasek s ***@***.***> napisał(a):

**Comment by robertsLando** [comment]
> How can I send a specific query to my meter, e.g. 68 03 03 68 53 01 b1 05 16?

You can't
