### ISSUE TITLE
mbus node crashes node-red

### ISSUE THREAD

**Issue by beireken** [robertsLando/node-red-contrib-m-bus#3]
I recentyly updated node-red to 0.20.3 (docker) and now node-red crashes on start.
When i remove the mbus node it works fine.

i get this output in the log:

```
at new MbusController (/data/node_modules/node-red-contrib-m-bus/mbus-controller.js:33:12)

at Object.createNode (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/util.js:483:31)
at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/Flow.js:176:44)
at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/nodes/flows/index.js:329:33)
at tryCatchReject (/usr/src/node-red/node_modules/when/lib/makePromise.js:845:30)
at runContinuation1 (/usr/src/node-red/node_modules/when/lib/makePromise.js:804:4)
at Fulfilled.when (/usr/src/node-red/node_modules/when/lib/makePromise.js:592:4)
at Pending.run (/usr/src/node-red/node_modules/when/lib/makePromise.js:483:13)
at Scheduler._drain (/usr/src/node-red/node_modules/when/lib/Scheduler.js:62:19)
at Scheduler.drain (/usr/src/node-red/node_modules/when/lib/Scheduler.js:27:9)
1 Apr 18:39:20 - [info] Started flows
1 Apr 18:39:20 - [info] [udp in:78fed0a4.839f1] udp listener at 0.0.0.0:10667
1 Apr 18:39:20 - [info] [tcp in:7efd7499.f2b0fc] listening on port 10666
1 Apr 18:39:20 - [info] [mqtt-broker:790af732.9eefd8] Connected to broker: mqtt://192.168.5.120:1883
1 Apr 18:39:20 - [info] [mqtt-broker:7920588d.5d6bd8] Connected to broker: mqtt://192.168.5.120:1883
1 Apr 18:39:20 - [error] [twitter in:red_nodes] Error: HTTP Error 401: Unauthorized

at /data/node_modules/twitter-ng/lib/twitter.js:65:17
at passBackControl (/data/node_modules/oauth/lib/oauth.js:397:13)
at IncomingMessage.<anonymous> (/data/node_modules/oauth/lib/oauth.js:409:9)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:139:11)
at process._tickCallback (internal/process/next_tick.js:181:9)
1 Apr 18:39:20 - [red] Uncaught Exception:
1 Apr 18:39:20 - Error: Module did not self-register.

at Object.Module._extensions..node (module.js:682:18)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at bindings (/data/node_modules/bindings/bindings.js:81:44)
at Object.<anonymous> (/data/node_modules/modbus-serial/node_modules/serialport/lib/bindings/linux.js:2:36)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.0 start: `node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1


npm ERR! Failed at the node-red-docker@1.0.0 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2019-04-01T16_39_20_801Z-debug.log

> node-red-docker@1.0.0 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js -v $FLOWS "--userDir" "/data"
```

Node.js is version 8.15.1

This probably has to do with the updated serialport package?
Ik had to update my modbus node for the same error.

**Comment by beireken** [comment]
hmm... i reinstalled all nodes that use the serialport node and it seems to hold now.
I'll see how it goes the next days!

**Comment by robertsLando** [comment]
Let me know! By checking your logs I don't see any error related to my node

**Comment by beireken** [comment]
Seems to be working fine for the last days!

**Comment by robertsLando** [comment]
Perfect thanks for your feedback!
